OpenVAA/voting-advice-application

frontend/src/app.css
frontend/src/app.html
frontend/src/lib/components/candidates/CandidateBasicInfo.svelte
frontend/src/lib/components/candidates/CandidateDetailsCard.svelte
frontend/src/lib/components/candidates/CandidateOpinions.svelte
frontend/src/lib/components/entityCard/EntityCard.svelte
frontend/src/lib/components/questions/LikertScaleAnsweringButtons.svelte
frontend/src/lib/components/questions/Question.svelte
frontend/src/lib/components/scoreGauge/ScoreGauge.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/shared/Tabs.svelte
frontend/src/lib/shared/card/Card.svelte
frontend/src/routes/(voters)/+layout.svelte
frontend/src/routes/(voters)/candidates/+page.svelte
frontend/src/routes/(voters)/candidates/[candidateId]/+page.svelte
frontend/src/routes/(voters)/navigation/+page.svelte
frontend/src/routes/(voters)/parties/+page.svelte
frontend/src/routes/(voters)/parties/[partyId]/+page.svelte
frontend/src/routes/(voters)/questions/+layout.svelte
frontend/src/routes/(voters)/questions/+page.svelte
frontend/src/routes/(voters)/questions/[questionId]/+page.svelte
frontend/src/routes/(voters)/results/+page.svelte
frontend/src/routes/(voters)/results/[candidateId]/+page.svelte
frontend/src/routes/+layout.svelte
frontend/src/routes/+page.svelte
frontend/tailwind.config.cjs

Fixes #135
Define a limited set of Tailwind utility classes for, e.g., spacing and font sizes, as well as the colours DaisyUI uses.
The reason for limiting Tailwind classes is that this way adherence to the design system is easier, because Tailwind gives nice autocomplete for the available options. For most classes names, such as `md` and `lg` are used. For spacing numeric values are also available, such as `w-40`, with the named ones, such as `gap-md`, reserved the most commonly used values.
Note that you can still use [arbitrary values](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values) with any Tailwind utility class with the bracket notation, e.g. `w-[21.35px]`.
For DaisyUI, all the [basic colours](https://daisyui.com/docs/colors/) are now defined for both the …

feat: redefine Tailwind utility classes, DaisyUI colors and apply default styles

---

docs/docker-setup-guide.md

Adding info to setup guide about how users can enable hot reloading for the Strapi backend.
Fixes issue #94 

docs: Add info about Strapi hot reloading

---

.env.example
.github/workflows/main.yaml
docs/docker-setup-guide.md

Couple of small improvements to onboarding documentation for new developers.

docs: Small fixes for better onboarding experience

---

frontend/src/lib/candidate/placeholder.json
frontend/src/lib/components/navigation/Navigation.svelte
frontend/src/lib/i18n/en.json
frontend/src/routes/candidate/+layout.svelte

Advances #192 
Add a temporary solution to candidate app navigation. This system will be replaced by the proper Navigation component once it is ready. This temporary solution is done to help the development of the candidate app.

feat: Add temporary navigation

---

.github/workflows/qa.yaml

Updating the QA pipeline to match current main CICD pipeline and running it on candidate-app branch as well.

Update QA pipeline & run it on candidate-app branch as well

---

README.md
docs/building-the-candidate-app/data-api.md
docs/building-the-candidate-app/frontend-app-separation.md
docs/contributing/CONTRIBUTING.md
docs/contributing/self-review.md
docs/contributing/style-guides.md
docs/frontend/styling.md
docs/troubleshooting.md
frontend/README.md

Fixes #219
Initial guidelines for writing Svelte components and
documenting them.
Some small issues I've run into together with their
solutions are collected in `docs/troubleshooting.md`.
Some guidelines for building the Candidate App are in the
`docs/building-the-candidate-app` folder. The need for these
was discussed in sprint 1 planning.

docs: building candidate app

---

frontend/src/lib/components/authentication/LoginPage.svelte
frontend/src/routes/candidate/+layout.svelte
frontend/src/routes/candidate/+page.svelte

After this change, you are required to login to access all routes within candidate app
The structure of the code was modified a bit

fix: authentication check

---

frontend/src/lib/components/authentication/AuthenticationProvider.svelte
frontend/src/lib/components/entityCard/EntityCard.svelte
frontend/src/lib/components/navigation/Navigation.svelte
frontend/src/lib/components/questions/Question.svelte
frontend/src/lib/components/shared/Tabs.svelte
frontend/src/routes/(voters)/navigation/+page.svelte
frontend/src/routes/(voters)/questions/+page.svelte
frontend/src/routes/+page.svelte
frontend/src/routes/candidate/profile/+page.svelte
frontend/yarn.lock

Fixes CI pipeline
`yarn prettier -w src` was run in the frontend directory

chore: format document

---

frontend/src/lib/components/navigation/TimedModal.svelte

Fixes https://github.com/orgs/OpenVAA/projects/2/views/1?pane=issue&itemId=44597483
Implements https://github.com/orgs/OpenVAA/projects/2/views/1?pane=issue&itemId=44575290
Fixes a bug that logged the user out even though the logout modal was not open.

fix: accidental logout and refactor

---

frontend/src/routes/candidate/register/+page.ts

Fixes bug which caused frontend to crash when registration page was refreshed by user after inputting registration code.
Server-side rendering was disabled for registration page.

fix: registration page refreshing

---

docs/candidate-app/password-validation.md
docs/candidate.app/password-validation.md

Advances #298 
Documentation for password validation, including frontend, backend and how to change the requirements.

docs: Password validation

---

frontend/src/lib/components/expander/Expander.svelte
frontend/src/lib/components/expander/Expander.type.ts
frontend/src/lib/components/expander/index.ts

Implements #58 Create a Expander component to be used throughout the application.
Implemented #58 

feat: create expander component

---

docs/candidate-app/candidates.md

Adds documentation regarding how login and registration are handled.
Only documentation was added.

feat: documentation around login/registration

---

frontend/src/lib/api/candidate.ts
frontend/src/lib/components/candidates/CandidateOpinions.svelte
frontend/src/lib/components/scoreGauge/ScoreGauge.svelte
frontend/src/lib/components/shared/Tabs.svelte
frontend/src/lib/utils/logger.ts
frontend/src/lib/voter/vaa-matching/examples/example.ts
frontend/src/lib/voter/vaa-matching/questions/hasMatchableQuestions.ts
frontend/tests/getData.test.ts

Fixes the CI pipeline in candidate-app
The tests were fixed and warnings are resolved

chore: fix ci pipeline

---

frontend/src/lib/api/candidate.ts
frontend/src/lib/candidate/components/logoutButton/LogoutButton.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/utils/authenticationStore.ts
frontend/src/routes/candidate/(protected)/settings/+page.svelte

Implements #206 
Adds a new user settings page per the mentioned issue above, with logic for updating the user's existing password.

Password change page

---

frontend/src/lib/api/candidate.ts
frontend/src/lib/components/answers/AnswerProvider.svelte
frontend/src/lib/components/answers/RequireAnswers.svelte
frontend/src/lib/i18n/en.json
frontend/src/lib/utils/answerStore.ts
frontend/src/routes/candidate/(protected)/+layout.svelte
frontend/src/routes/candidate/(protected)/+page.svelte
frontend/src/routes/candidate/(protected)/questions/+layout.server.ts
frontend/src/routes/candidate/(protected)/questions/+layout.svelte
frontend/src/routes/candidate/(protected)/questions/+page.svelte
frontend/src/routes/candidate/(protected)/questions/[questionId]/+layout.svelte
frontend/src/routes/candidate/(protected)/questions/[questionId]/+page.svelte

Advances #198
Candidates can answer multiple choice questions and those questions are saved to and retrieved from the database.

feat: Answer multiple choice statements

---

frontend/src/lib/api/candidate.ts
frontend/src/lib/candidate/components/answers/AnswerProvider.svelte
frontend/src/lib/candidate/components/answers/RequireAnswers.svelte
frontend/src/lib/candidate/components/answers/index.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/utils/answerStore.ts
frontend/src/routes/candidate/(protected)/questions/+layout.server.ts
frontend/src/routes/candidate/(protected)/questions/+layout.svelte
frontend/src/routes/candidate/(protected)/questions/+page.svelte
frontend/src/routes/candidate/(protected)/questions/[questionId]/+layout.svelte
frontend/src/routes/candidate/(protected)/questions/[questionId]/+page.svelte

Implements #198 
A new /candidate/questions route has been added, where the candidate is able answer multiple choice statements.
The answers are saved to the database when an option is selected. Previous answers are also loaded from the database, which enables changing the answer to a question.
The display of the choices is visually as close to the voter's view of the same questions as possible.

feat: Answering multiple choice statements as a candidate

---

frontend/src/lib/api/candidate.ts
frontend/src/lib/i18n/en.json
frontend/src/lib/templates/page/parts/CandidateNav.svelte
frontend/src/lib/utils/answerStore.ts
frontend/src/routes/candidate/(protected)/questions/[questionId]/+page.svelte

Implements #199 
Adds the open answer field for candidate questions. Answers are saved locally and when the candidate navigates to another questions, the answers are saved to database.

feat: Candidate open answers

---

frontend/src/lib/i18n/en.json

Fixes a styling issue in i18n
Fixes a styling issue in i18n

fix: remove new line from i18n

---

frontend/src/routes/candidate/(protected)/questions/[questionId]/+page.svelte
frontend/src/routes/candidate/(protected)/questions/all/+page.svelte

Removes unnecessary delay from candidate questions.
Delay has been removed. Question now changes instantly.

refactor: candidate question navigation

---

backend/vaa-strapi/src/extensions/users-permissions/strapi-server.js
frontend/src/lib/i18n/en.json
frontend/src/routes/candidate/(protected)/profile/+page.svelte

Fixes a few bugs in #193 and adds the required backend permissions for #203 

Feature/193 basic info page small fixes & backend permissions

---

frontend/src/lib/api/candidate.ts
frontend/src/lib/api/getData.type.ts
frontend/src/lib/candidate/components/answers/AnswerProvider.svelte
frontend/src/lib/candidate/components/answers/RequireAnswers.svelte
frontend/src/lib/components/infoBadge/index.ts
frontend/src/lib/components/infoBadge/infoBadge.svelte
frontend/src/lib/components/infoBadge/infoBadge.type.ts
frontend/src/lib/components/navigation/NavItem.svelte
frontend/src/lib/templates/page/parts/CandidateNav.svelte
frontend/src/lib/utils/answerStore.ts
frontend/src/routes/[[lang=locale]]/candidate/(protected)/+layout.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/+layout.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/summary/+page.svelte

feat: Implement badge component

---

backend/vaa-strapi/src/api/answer/routes/answer.ts
backend/vaa-strapi/src/api/question-category/routes/question-category.ts
backend/vaa-strapi/src/api/question/routes/question.ts
backend/vaa-strapi/src/util/acl.ts
frontend/src/lib/api/candidate.ts

Fixes some missing ACL options.

fix: missing permissions from recently merged changes

---

frontend/package.json
frontend/src/lib/components/openVAALogo/OpenVAALogo.svelte
frontend/src/lib/components/questions/LikertResponseButtons.svelte
frontend/src/lib/components/scoreGauge/ScoreGauge.svelte
frontend/tailwind.config.cjs
frontend/yarn.lock

Fixes #256 
Also, make necessary fixes to `tailwind.config.cjs` and the `ScoreGauge` and `LikertResponseButtons` components that use the DaisyUI color CSS vars (see below).
BREAKING CHANGE: `hsl(var(--n))` and similar CSS var calls have to be changed to `oklch(var(--n))`.
See also:
https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md#400-2023-11-12i
Includes also a quick fix to the `OpenVAALogo` component.

build(deps)!: update to DaisyUI 4.7.2

---

backend/vaa-strapi/src/api/candidate/content-types/candidate/schema.json
backend/vaa-strapi/src/api/gender/content-types/gender/schema.json
backend/vaa-strapi/src/api/gender/controllers/gender.ts
backend/vaa-strapi/src/api/gender/documentation/1.0.0/gender.json
backend/vaa-strapi/src/api/gender/routes/gender.ts
backend/vaa-strapi/src/api/gender/services/gender.ts
backend/vaa-strapi/src/extensions/documentation/documentation/1.0.0/full_documentation.json
backend/vaa-strapi/src/extensions/users-permissions/strapi-server.js
backend/vaa-strapi/src/functions/generateMockData.ts
backend/vaa-strapi/types/generated/contentTypes.d.ts
frontend/src/lib/api/candidate.ts
frontend/src/lib/api/getData.type.ts
frontend/src/lib/types/candidateAttributes.ts
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/AvatarSelect.svelte

Improves features implemented in #193 

Polish basic info page and add gender enumeration to backend

---

frontend/src/lib/api/candidate.ts
frontend/src/lib/candidate/components/textArea/TextArea.type.ts
frontend/src/lib/components/preventNavigation/PreventNavigation.svelte
frontend/src/lib/components/preventNavigation/index.ts
frontend/src/lib/types/candidateAttributes.ts
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte
tests/candidate.spec.ts

feat: Implement PreventNavigation component

---

.github/workflows/main.yaml
backend/vaa-strapi/docker-compose.dev.yml
backend/vaa-strapi/docker-compose.yml
frontend/docker-compose.dev.yml
frontend/docker-compose.yml
package.json
tests/candidate.spec.ts
tests/global-setup.ts

Runs E2E tests in main for quality assurance.

feat: run e2e in CI

---

.github/workflows/main.yaml
tests/candidate.spec.ts

Fixes E2E tests due to not properly supporting the main branch

fix: e2e tests

---

frontend/src/lib/candidate/templates/login/LoginPage.svelte
frontend/src/routes/[[lang=locale]]/candidate/register/PasswordSetPage.svelte

Fixes #410
Pressing the "set password" button now logs out any user currently logged in

Feat 410: Registering a user now logs out any user currently logged in

---

frontend/src/lib/candidate/components/PasswordField/PasswordField.svelte
frontend/src/lib/candidate/components/textArea/MultilangTextInput.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/settings/+page.svelte

Fixes accessibility issues and bug with profile page fill status
Fixes bug where profile page fill status was incorrectly checked after the new localized text areas.
Fixes accessibility issues with multi-language text area.

fix: profile page fill state and accessibility

---

backend/vaa-strapi/src/api/question-category/routes/question-category.ts
backend/vaa-strapi/src/functions/generateMockData.ts

Fixes preview page not loading

fix: preview page not loading

---

backend/vaa-strapi/config/plugins.ts

feat: set JWT lifetime to 4 hours

---

backend/vaa-strapi/src/api/answer/routes/answer.ts

Fixes not being able to answer questions for now.
The election canEditQuestion logic depended on the current answer, which isn't possible to actually check on answer creation. This has been refactored in favor of checking candidate -> nominations -> election (which eventually would be candidate -> nomination -> election) to fix this.

fix: answering questions for now

---

frontend/src/lib/components/preventNavigation/PreventNavigation.svelte
frontend/src/lib/i18n/translations/en/candidateApp.json
frontend/src/lib/i18n/translations/fi/candidateApp.json
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte

fix: prevent navigation on pathname change

---

frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte

fix: Let the user navigate away from the profile page after they done

---

backend/vaa-strapi/src/plugins/candidate-admin/admin/src/extensions/RegistrationEmailButton.tsx
backend/vaa-strapi/src/plugins/candidate-admin/admin/src/extensions/RegistrationEmailToAll.tsx
backend/vaa-strapi/src/plugins/candidate-admin/admin/src/extensions/RegistrationEmailToOne.tsx
backend/vaa-strapi/src/plugins/candidate-admin/server/controllers/email.js
backend/vaa-strapi/src/plugins/candidate-admin/server/services/email.js

Improves registration email sending.

refactor: improve registration email

---

backend/vaa-strapi/src/api/nomination/routes/nomination.ts
backend/vaa-strapi/src/functions/generateMockData.ts
backend/vaa-strapi/src/functions/setDefaultApiPermissions.ts
frontend/src/lib/api/getData.ts
frontend/src/lib/api/getData.type.ts
frontend/src/lib/components/candidates/CandidateBasicInfo.svelte
frontend/src/lib/i18n/translations/en/candidate.json
frontend/src/lib/i18n/translations/fi/candidate.json
frontend/src/lib/types/global.d.ts
tests/global-setup.ts

Fixes candidate preview not showing the correct basic info.

fix: candidate preview not showing correct basic info

---

backend/vaa-strapi/src/api/answer/routes/answer.ts
backend/vaa-strapi/src/api/candidate/content-types/candidate/schema.json
backend/vaa-strapi/src/api/candidate/routes/candidate.ts
backend/vaa-strapi/src/api/nomination/content-types/nomination/schema.json
backend/vaa-strapi/src/extensions/users-permissions/strapi-server.js
backend/vaa-strapi/src/util/acl.ts
backend/vaa-strapi/types/generated/contentTypes.d.ts
frontend/src/lib/api/candidate.ts
frontend/src/lib/api/getData.ts
frontend/src/lib/candidate/templates/question/QuestionPage.svelte
frontend/src/lib/components/common/form/Field.svelte
frontend/src/lib/components/common/form/FieldGroup.svelte
frontend/src/lib/components/warning/Warning.svelte
frontend/src/lib/i18n/translations/en/candidateApp.json
frontend/src/lib/i18n/translations/fi/candidateApp.json
frontend/src/lib/types/candidateAttributes.ts
frontend/src/lib/types/global.d.ts
frontend/src/lib/utils/candidateStore.ts
frontend/src/routes/[[lang=locale]]/candidate/(protected)/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/AvatarSelect.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/InputContainer.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/+page.svelte

Implements the rest of the features in #210.

feat: don't allow modification if answers are locked and display a notification (#210)

---

frontend/src/lib/candidate/components/candidateContext/RequireLogin.svelte
frontend/src/lib/components/button/Button.svelte
frontend/src/lib/components/expander/Expander.svelte
frontend/src/lib/components/modal/TimedModal.svelte
frontend/src/lib/i18n/translations/en/candidateApp.json
frontend/src/lib/i18n/translations/fi/candidateApp.json
frontend/src/lib/types/candidateAttributes.ts
frontend/src/lib/utils/candidateStore.ts

fix: correct errors with accessibility navigation and fix small bugs

---

backend/vaa-strapi/src/api/candidate/content-types/candidate/lifecycles.ts

fix: disallow null manifesto

---

frontend/src/lib/i18n/translations/en/candidateApp.json
frontend/src/lib/i18n/translations/fi/candidateApp.json
frontend/src/lib/i18n/translations/translations.type.ts
frontend/src/routes/[[lang=locale]]/candidate/(protected)/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/register/+page.svelte
frontend/src/routes/[[lang=locale]]/candidate/register/PasswordSetPage.svelte

Improves user experience and fixes typo
Adds a close preview button to candidate preview, which takes the user the home page. In addition, fixes a typo regardin username/userName.

feat: close preview button

---

frontend/src/lib/api/candidate.ts

chore: Improve candidate api code quality

---

README.md

docs: add project description to README

---

.github/dependabot.yml
docs/contributing/how-to-use-labels.md

fix: update label docs

---

frontend/src/lib/utils/answers.ts

Minor improvements to the utilities.
Make the `getAnswer` and `getAnswerForDisplay` utilities a bit more
robust, deal properly with invalid Dates and tidy up code.

refactor: answer utility

---

backend/vaa-strapi/Dockerfile
backend/vaa-strapi/docker-compose.yml
frontend/Dockerfile

Fixes #394 
`depends_on` has been removed from `vaa-strapi/docker-compose.yml` because it caused issues with some Docker versions and doesn't seem to be necessary as it has already been removed from `vaa-strapi/docker-compose.dev.yml` four months ago.
Keywords in Dockerfiles has been changed to uppercase as it isn't recommended to mix lowercase and uppercase keywords.

build: fix docker issues

---

backend/vaa-strapi/docker-compose.dev.yml

Fix the volume path to match the new folder structure with workspaces.

fix: backend hot reloading

---

packages/factor-analysis/.gitignore
packages/factor-analysis/README.md
packages/factor-analysis/package.json
packages/factor-analysis/src/api.test.ts
packages/factor-analysis/src/api.ts
packages/factor-analysis/src/api.type.ts
packages/factor-analysis/src/factorAnalysis.test.ts
packages/factor-analysis/src/factorAnalysis.ts
packages/factor-analysis/src/factorAnalysis.type.ts
packages/factor-analysis/src/index.ts
packages/factor-analysis/src/polychoric/correlation.test.ts
packages/factor-analysis/src/polychoric/correlation.ts
packages/factor-analysis/src/polychoric/correlation.type.ts
packages/factor-analysis/src/polychoric/index.ts
packages/factor-analysis/src/polychoric/matrix.test.ts
packages/factor-analysis/src/polychoric/matrix.ts
packages/factor-analysis/src/types/index.ts
packages/factor-analysis/src/utils/normalDistribution.ts
packages/factor-analysis/src/utils/statisticalUtils.test.ts
packages/factor-analysis/src/utils/statisticalUtils.ts
packages/factor-analysis/tsconfig.json
packages/factor-analysis/vitest.config.ts

This PR adds a new factor analysis package that provides essential statistical functionality for analyzing questionnaire responses, including polychoric correlation computation and factor analysis. 
Fixes #[Issue number] (Please add the actual issue number)
- Added new `@openvaa/factor-analysis` package
- Implemented polychoric correlation computation
- Implemented factor analysis with varimax rotation
- Added comprehensive unit tests with >90% coverage
- Added detailed documentation including API usage examples
- Included numerical stability improvements for edge cases

feat(factor-analysis): add factor analysis package
