OpenVAA/voting-advice-application

frontend/src/routes/(voters)/questions/+page.svelte
Small fix to make questions intro page text look nicer for the demo. Replaces {{0}} and {(1}} with actual numbers based on the number of questions
Page layout on questions page.
=> fix: Format description text numbers properly in questions intro page

frontend/tailwind.config.cjs
Fix AA-level colour contrast errors when checking with the Wave extension.
Change DaisyUI colours so that they fulfill the AA level of colour
contrast in all combinations.
=> Fix colour contrast

backend/vaa-strapi/src/functions/generateMockData.ts, backend/vaa-strapi/src/functions/mockCategories.json
Just a small change to add more realistic question categories to mock data generation instead of always generating faker data. Hopefully makes user testing bit nicer.
Mock data generation
=> feat: Add more realistic question categories to mock data generation

docs/contributing/self-review.md
As discussed in the Aalto SWP 1 sprint 0 meeting,
checking the code for most common cyber security
issues is now included in self review.
Because `style-guides.md` is currently empty,
it's removed from the checklist but should be
reintroduced once we have such a guide.
Decided in the Aalto SWP 1 sprint 0 meeting.
=> docs: add security to self review and remove style

frontend/src/lib/components/authentication/LoginPage.svelte, frontend/src/lib/components/footer/Footer.svelte
Implements the footer as a component so it's easier to reuse it between pages (as based on the Figma not all pages have the footer).
=> Footer component

frontend/src/lib/components/navigation/NavGroup.svelte, frontend/src/lib/components/navigation/NavGroup.type.ts, frontend/src/lib/components/navigation/NavItem.svelte, frontend/src/lib/components/navigation/NavItem.type.ts, frontend/src/lib/components/navigation/Navigation.svelte, frontend/src/lib/components/navigation/Navigation.type.ts, frontend/src/lib/components/navigation/index.ts, frontend/tailwind.config.cjs
Necessary for #214 and related to #60.
The `Navigation` component takes as its input a list of `NavigationItems` and outputs a properly formatted navigation element with the items as links or buttons depending on whether a `href` or `onclick` property is provided for them.
The logic for creating the actual items is separated from the component so that the lists of `NavigationItems` can be contained in stores placed in the `$voter` and `$candidate` libraries.
The component will mainly be used in the page templates.
=> feat: navigation component

.env.example, docker-compose.dev.yml, docker-compose.yml, frontend/src/lib/utils/constants.ts
Logging into candidate app did not work on production build, as built Svelte app was unable to access the backend URL and send login info. Received error:
```
5.febffbc8.js:1 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
at dr (5.febffbc8.js:1:4074)
at Object._r [as logIn] (5.febffbc8.js:1:4680)
at HTMLFormElement.d (5.febffbc8.js:7:6045)
at HTMLFormElement.<anonymous> (index.acd0945c.js:1:3560)
```
This error was because the URL given was undefined. You can see this error in action in https://demo.openvaa.org/candidate
Changed how backend URL environment variable is imported so it is accessible by the client-side app as well.
To test the changes, set environment variables correctly as in the PR files, run `npm run prod`, go to http://localhost/candidate and …
=> fix: Make candidate app login work on production build

backend/vaa-strapi/.prettierignore, frontend/.prettierignore
Adding package.json to .prettierignore file as we do not need to check formatting for that. You can see PR #262 having issue with that in the CI pipeline so adding this will probably solve the problem.
=> chore: Add package.json to prettierignore file

backend/vaa-strapi/docker-compose.dev.yml, backend/vaa-strapi/docker-compose.yml, docker-compose.dev.yml, docker-compose.yml, package.json
Currently, some people have issues with starting the project due to the Postgres container's data folder having changed ownership due to mismatching users between the host and the container. This leads to people having to run "chmod -R 777" each time when testing some of the changes.
The bind mount has been replaced with volumes so that Docker will be fully responsible for figuring out the folder's correct permissions. Additionally, I've added `--force-recreate` flag for the dev commands so that `.env` and docker compose changes always propagate.
=> Use docker volume over bind mounts for postgres

frontend/src/lib/components/button/Button.svelte, frontend/src/lib/components/button/Button.type.ts, frontend/src/lib/components/button/index.ts, frontend/tailwind.config.cjs
Fixes #250 
Introduces three components for common button types used throughout the application as well as a base component for these:
- `ButtonBase`: the base component for these buttons
- `MainButton` for the main action button of a page
- `SecondaryButton` for secondary actions, such as those under an opinion questions answers or for sorting a list
- `IconButton` for buttons that only contain an icon
To see the buttons in action, see the temporary `_test` route.
=> feat: button components

frontend/src/lib/components/navigation/Navigation.svelte, frontend/src/lib/components/navigation/TimedModal.svelte
Fixes https://github.com/orgs/OpenVAA/projects/2/views/1?pane=issue&itemId=45145874
Timed modal text was black even in dark mode, making it invisible. Now the text is white and the modal is more visible in general.
=> fix: modal is visible in dark mode

docs/frontend/color-test.txt, docs/frontend/styling.md, frontend/tailwind.config.cjs
Fixes #285 
1. Some color definitions are changed so that all the normal color combinations have AA-level contrast.
2. Redefined the `base-200` color to match Figma designs.
3. Added information about testing the color contrasts to `docs/frontend` as well as a file that can be used to test them.
=> fix: color contrast issues globally

frontend/src/lib/components/common/FieldGroup.svelte, frontend/src/routes/candidate/profile/+page.svelte
Matches the basic information UI with Figma. Does not implement lock icons or button yet due to the icons being only present in the `main` branch.
Basic information UI has changed.
=> feat: match basic information UI to Figma

.env.example, backend/vaa-strapi/config/env/development/plugins.ts, backend/vaa-strapi/config/plugins.ts, backend/vaa-strapi/package.json, backend/vaa-strapi/src/extensions/users-permissions/content-types/user/schema.json, backend/vaa-strapi/src/extensions/users-permissions/strapi-server.js, backend/vaa-strapi/yarn.lock, docker-compose.dev.yml, docs/admin-guide/candidate-app.md, frontend/src/lib/api/candidate.ts, package.json
Introduced the required backend logic for #189 
Added SMTP configuration and a maildev container for local development so that developers do not need to use real credentials. Additionally, this removes the `-v` flag from the `dev:down` command due to it deleting the volumes (and thus all Strapi data).
=> feat: forgot password backend

backend/vaa-strapi/config/typescript.ts, backend/vaa-strapi/src/api/candidate-attribute/content-types/candidate-attribute/schema.json, backend/vaa-strapi/src/api/candidate-attribute/controllers/candidate-attribute.ts, backend/vaa-strapi/src/api/candidate-attribute/documentation/1.0.0/candidate-attribute.json, backend/vaa-strapi/src/api/candidate-attribute/routes/candidate-attribute.ts, backend/vaa-strapi/src/api/candidate-attribute/services/candidate-attribute.ts, backend/vaa-strapi/src/api/candidate/content-types/candidate/schema.json, backend/vaa-strapi/src/extensions/documentation/documentation/1.0.0/full_documentation.json, backend/vaa-strapi/src/functions/generateMockData.ts, backend/vaa-strapi/tsconfig.json, backend/vaa-strapi/types/generated/components.d.ts, backend/vaa-strapi/types/generated/contentTypes.d.ts, frontend/src/lib/components/common/FieldGroup.svelte
Fixes #296 
A new content type was added and it was populated using the generate mock data file.
This doesn't change any functionality and the old fields are intentionally left in Strapi.
=> feat: create candidate attributes content type

docs/contributing/style-guides.md, frontend/src/app.css, frontend/src/lib/components/button/Button.svelte, frontend/src/lib/components/button/Button.type.ts, frontend/src/lib/components/headingGroup/HeadingGroup.svelte, frontend/src/lib/components/headingGroup/HeadingGroup.type.ts, frontend/src/lib/components/headingGroup/PreHeading.svelte, frontend/src/lib/components/headingGroup/PreHeading.type.ts, frontend/src/lib/components/heroEmoji/HeroEmoji.svelte, frontend/src/lib/components/icon/Icon.svelte, frontend/src/lib/components/navigation/NavGroup.svelte, frontend/src/lib/components/navigation/NavItem.svelte, frontend/src/lib/components/navigation/NavItem.type.ts, frontend/src/lib/templates/basicPage/BasicPage.svelte, frontend/src/lib/templates/frontPage/FrontPage.svelte, frontend/src/lib/templates/page/Page.svelte, frontend/src/lib/templates/parts/appLogo/AppLogo.svelte, frontend/src/lib/templates/singleCardPage/SingleCardPage.svelte, frontend/src/lib/utils/components.ts
Fixes: #278 
Components and templates using `$$restProps` forwarding had an issue with reactive
updates that would lead to layouts breaking. The reason for this was that the
`class` string used by the components were merged into `$$restProps` in a
non-reactive part of the component and the `$$restProps` was passed
directly to the component with the expectation that it would contain the proper
`class` string. However, any reactive updates would reinstantialize 
`$$restProps` and the alterations would no longer be included in it.
This issue became very prominent with the introduction of page templates,
because any reactive update to a page's contents, would break the layout
due to the loss of  `class="drawer"` in the `<div>` containing the page,
which was also described in #278.
In this …
=> fix: reactivity issues in components and templates

backend/vaa-strapi/src/api/candidate-attribute/content-types/candidate-attribute/schema.json, backend/vaa-strapi/src/api/question/content-types/question/schema.json, backend/vaa-strapi/src/extensions/documentation/documentation/1.0.0/full_documentation.json, backend/vaa-strapi/types/generated/contentTypes.d.ts, frontend/src/lib/api/getData.ts, frontend/src/lib/api/getData.type.ts, frontend/src/lib/types/global.d.ts
Advances [#201](https://github.com/OpenVAA/voting-advice-application/issues/201)
Adds fillingInfo field to the Question and Candidate Attributes content types in strapi.
=> Feat: fillingInfo fields to strapi (#201)

backend/vaa-strapi/.eslintrc.json, frontend/.eslintrc.json, frontend/src/routes/_test/+page.svelte
Fixes #323 
Conflicts Eslint's and Prettier's opinions cause some checks always to fail.
Running on the automatic check `npx eslint-config-prettier ./frontend/.eslintrc.json` reports:
```
The following rules are unnecessary or might conflict with Prettier:
- indent
- linebreak-style
- semi
The following rules are enabled but cannot be automatically checked. See:
https://github.com/prettier/eslint-config-prettier#special-rules
- quotes
```
This is due to the fact that `eslint-config-prettier` cannot automatically turn off rules, only defaults.
To fix, the first three rules need to be removed, and the `quotes` one edited and kept in sync with Prettier:
Eslint:
```
{
"rules": {
"quotes": [
"error",
"single",
{ "avoidEscape": true, "allowTemplateLiterals": false }
]
}
}
```
Prettier:
```
{ …
```
=> build: fix Eslint and Prettier conflicts

frontend/src/lib/candidate/components/textArea/TextArea.svelte, frontend/src/lib/candidate/components/textArea/TextArea.type.ts, frontend/src/lib/candidate/components/textArea/index.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/[questionId]/+page.svelte
Implements #212 
Adds a new TextArea component that can be used for open answers in the candidate app. The component features an auto save feature where changes can be saved to local storage before sending them to the database.
The component has been taken into use in the candidate questions page (open answer to a question) and the basic info page (election manifesto). This PR also fixes the candidate questions background color.
=> feat: TextArea component with local autosave

backend/vaa-strapi/src/api/app-setting/content-types/app-setting/schema.json, backend/vaa-strapi/src/api/app-setting/controllers/app-setting.ts, backend/vaa-strapi/src/api/app-setting/documentation/1.0.0/app-setting.json, backend/vaa-strapi/src/api/app-setting/routes/app-setting.ts, backend/vaa-strapi/src/api/app-setting/services/app-setting.ts, backend/vaa-strapi/src/api/nomination/routes/nomination.ts, backend/vaa-strapi/src/api/party/content-types/party/schema.json, backend/vaa-strapi/src/api/question-category/content-types/question-category/schema.json, backend/vaa-strapi/src/api/question/content-types/question/schema.json, backend/vaa-strapi/src/extensions/documentation/documentation/1.0.0/full_documentation.json, backend/vaa-strapi/src/functions/generateMockData.ts, backend/vaa-strapi/src/functions/setDefaultApiPermissions.ts, backend/vaa-strapi/types/generated/components.d.ts, backend/vaa-strapi/types/generated/contentTypes.d.ts
Fixes #389
Fixes #417 
Introduces various small updates to:
- Create an `App Settings` content type for future use
- Add color and `colorDark` properties to Party and `Question
Category`
- Add `customData` property to `Question`, which can be used to store
data specific to an app instance
- Update access control policies to fix bugs with retrieving `Parties`
and individual `Candidates`.
=> feat: update Strapi content model

frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.server.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/+layout.server.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/summary/+page.svelte
Fixes some localisation issues in the Candidate App.
Make server-based data fetching dependent on `parent`'s `i18n.currentLocale`.
Make `export let data` assignments reactive so that localised texts contained in them are updated.
=> fix: localisation issues in the Candidate App

frontend/src/lib/i18n/translations/en/candidateApp.json, frontend/src/lib/i18n/translations/fi/candidateApp.json, frontend/src/lib/templates/singleCardPage/SingleCardPage.svelte, frontend/src/lib/templates/singleCardPage/SingleCardPage.type.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.server.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/+layout.server.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/summary/+page.svelte
Fixes feedback received from users
Adds a note explaining what the preview of a candidate's profile is.
This requires also adding a similar `note` slot to `SingleCardPage` as on `BasicPage` for displaying notifications.
=> feat: info note on candidate app preview

backend/vaa-strapi/src/api/candidate/content-types/candidate/lifecycles.ts
Password resetting didn't work if the email of the user wasn't in lowercase. This caused issues when creating users for candidates that had email that wasn't in lowercase.
Email field is made lowercase when creating or updating candidate. 
=> fix: password resetting bug

backend/vaa-strapi/src/api/candidate/content-types/candidate/schema.json, backend/vaa-strapi/src/api/candidate/routes/candidate.ts, backend/vaa-strapi/src/extensions/users-permissions/strapi-server.js, frontend/src/lib/api/candidate.ts, frontend/src/lib/candidate/templates/login/LoginPage.svelte, frontend/src/lib/i18n/translations/en/candidateApp.json, frontend/src/lib/i18n/translations/fi/candidateApp.json, frontend/src/lib/types/candidateAttributes.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/settings/+page.svelte
Finishes [#202](https://github.com/OpenVAA/voting-advice-application/issues/202)
User can now change their application language preference in the settings page. The preference is saved in the candidate object and the user is redirected to correct language route (if the preference has been set) when logging in.
=> Feat/202 select UI language

frontend/src/lib/candidate/components/textArea/InputField.svelte, frontend/src/lib/candidate/components/textArea/MultilangTextInput.svelte, frontend/src/lib/candidate/components/textArea/TextArea.svelte, frontend/src/lib/candidate/components/textArea/TextArea.type.ts
Advances #210 
Adds support for the TextArea component to be locked when candidates can no longer edit their answers.
=> feat: locked textarea

backend/vaa-strapi/src/api/answer/routes/answer.ts
Enforces that the candidate can't create/update/delete questions if disabled for the election.
=> feat: enforce question editing on the backend

frontend/src/lib/candidate/templates/login/LoginPage.svelte, frontend/src/lib/i18n/translations/en/candidateApp.json
Made "password set" message fit inside the standard width area 
=> fix: make password set message look better

frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte
Fixes being able to enter an unrealistic birthday.
The date input now enforces birthday to be between year 1800 and current date.
=> fix: restrict birthday range

frontend/src/lib/candidate/components/candidateContext/CandidateContextProvider.svelte, frontend/src/lib/candidate/components/candidateContext/RequireAnswers.svelte, frontend/src/lib/candidate/components/candidateContext/RequireLogin.svelte, frontend/src/lib/candidate/components/loadingSpinner/LoadingSpinner.svelte, frontend/src/lib/candidate/components/loadingSpinner/index.ts, frontend/src/lib/candidate/components/logoutButton/LogoutButton.svelte, frontend/src/lib/candidate/components/passwordField/PasswordField.svelte, frontend/src/lib/candidate/components/passwordSetter/PasswordSetter.svelte, frontend/src/lib/candidate/components/passwordValidator/PasswordValidator.svelte, frontend/src/lib/candidate/components/questionsPage/QuestionsStartPage.svelte, frontend/src/lib/candidate/templates/question/QuestionPage.svelte, frontend/src/lib/i18n/translations/en/candidateApp.json, frontend/src/lib/i18n/translations/fi/candidateApp.json, frontend/src/lib/templates/page/Page.svelte, frontend/src/lib/types/candidateAttributes.ts, frontend/src/lib/utils/candidateStore.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/profile/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/+layout.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/questions/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/(protected)/settings/+page.svelte, frontend/src/routes/[[lang=locale]]/candidate/register/RegistrationCodePage.svelte
Implements the progress bar in candidate app.
The candidate app now uses the progress bar of the Page component.
Additionally, improves UX by adding loading indicators to profile preview and checking the basic page fill status on
/questions route. A basic loading spinner component is added to standardize the style of loading indicators.
=> feat: candidate app progress bar

frontend/src/lib/components/candidates/CandidateDetailsCard.svelte, frontend/src/lib/components/candidates/CandidateOpinions.svelte, frontend/src/lib/types/global.d.ts, frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.svelte
The candidate preview texts have been fixed to show correct information.
Modified CandidateDetailsCard and CandidateOpinions component to show different texts based on the application side they are used.
=> fix: candidate preview texts

backend/vaa-strapi/src/api/candidate/content-types/candidate/lifecycles.ts
Manifesto was null instead of {} when candidate was imported or created in Strapi.
=> fix: candidate manifesto creation

frontend/src/lib/candidate/components/questionsPage/AnsweredQuestion.svelte, frontend/src/lib/candidate/components/questionsPage/QuestionsStartPage.svelte, frontend/src/lib/candidate/components/questionsPage/UnAnsweredQuestion.svelte
Adds documentation to AnsweredQuestion.svelte, QuestionsStartPage.svelte and UnAnsweredQuestions.svelte
Adds documentation to AnsweredQuestion.svelte, QuestionsStartPage.svelte and UnAnsweredQuestions.svelte
=> fix: add documentation to candidate app

docs/candidate-app/import-functionality.md
Import plugin originally had option tab in import editor. This was removed because we don't need it.
=> fix: remove unnecessary options from importEditor

frontend/src/lib/templates/page/parts/CandidateNav.svelte
Temporarily disable three navbuttons
=> temporarily disable three navbuttons

.env.example, backend/vaa-strapi/.env.example, backend/vaa-strapi/Dockerfile, backend/vaa-strapi/config/plugins.ts, backend/vaa-strapi/config/server.ts, backend/vaa-strapi/docker-compose.dev.yml, backend/vaa-strapi/docker-compose.yml, docker-compose.dev.yml, docker-compose.yml, frontend/Dockerfile, frontend/docker-compose.dev.yml, frontend/docker-compose.yml, frontend/vite.config.ts, package.json, playwright.config.ts, tests/register.spec.ts, yarn.lock
Advances #559 
`version` has been removed from docker-compose(.dev).yml files because it was obsolete:
```
WARN[0000] /home/antti/Documents/voting-advice-application/docker-compose.dev.yml: `version` is obsolete
```
Unnecessarry `--` has been removed from yarn commands in Dockerfiles:
```
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
```
`candidate` field has been added to [Strapi plugin config](https://docs.strapi.io/dev-docs/plugins/users-permissions#configuration):
```
warn: Users-permissions registration has defaulted to accepting the following additional user fields during registration: candidate
```
Strapi data transfer feature has been …
=> Fix warnings

frontend/src/routes/[[lang=locale]]/(voters)/results/+page.svelte, frontend/src/routes/[[lang=locale]]/(voters)/results/page-stores.ts
Fixes #568 
Results tab is persisted with snapshot instead of store.
=> refactor: results tab persists state with snapshot

frontend/src/routes/[[lang=locale]]/candidate/(protected)/preview/+page.svelte
Fixes bug when changing languages (close button would navigate back to the previous language).
Update the button action so that it works properly also after having changed the language.
=> fix: close button behaviour in Candidate preview

frontend/src/lib/components/entityDetails/EntityInfo.svelte, frontend/src/lib/components/entityDetails/InfoItem.svelte
Fixes [Issue link](https://github.com/orgs/OpenVAA/projects/7?pane=issue&itemId=69315433)
For answers to questions with "text" type:
- we use vertical layout (as in "no columns but rows") now.
- label has unlimited width to compliment / benefit from the vertical layout.
- the vertical layout item got extra bottom padding to separate itself from the following horizontal items visually.
I also increased the column width for all labels - as of now the answers column is supposed to contain only short text and the labels can benefit from some extra width for readability.
=> feat: Vertical layout for candidate text answers

frontend/src/lib/components/entityCard/EntityCard.svelte, frontend/src/lib/i18n/README.md, frontend/src/lib/i18n/translations/en/about.json, frontend/src/lib/i18n/translations/fi/about.json, frontend/src/lib/utils/filters.ts, frontend/src/lib/utils/matching/LikertQuestion.ts, frontend/tools/editTranslations/editTranslations.ts
Fixes some small issues encountered when working on the settings refactoring.
- EntityCard spacing when subcards are empty. Removes some margin when the subcards `div` is empty, although due to
whitespace issues this will only have effect with Svelte 5.
- Remove line breaks from translations. Line breaks (and other special characters) cause problems when exporting
and reimporting translations, because the backslashes get escaped. Removes these from the existing translations and updates docs.
- Fix missing party filter translation. Change the party filter name translation to just the party term.
- Fix undefined values in Likert question matching. Properly returns the `undefined` value instead of a `'undefined'` string if the value is missing.
**Clean up your git commit history before …
=> fix: various small fixes

backend/vaa-strapi/package.json, frontend/package.json, package.json, packages/shared-config/package.json, yarn.lock
Nb. This downgrade should've been in the yarn 4 update PR but was lost due to rebase.
An `eslint`/`typescript-eslint` bug breaks `eslint` from 9.15 on.
See: https://github.com/eslint/eslint/issues/19134
See: https://github.com/typescript-eslint/typescript-eslint/issues/10338
Note that the updated `typescript-eslint` does not seem to fix the issue, perhaps bc some related deps are not updated.
=> build: downgrade `eslint` to 9.14

frontend/src/lib/contexts/layout/layoutContext.ts, frontend/src/lib/contexts/layout/layoutContext.type.ts, frontend/src/routes/[[lang=locale]]/Header.svelte, frontend/src/routes/[[lang=locale]]/Layout.svelte
Fixes #677 
Add an option to hide the navigation menu for use on, e.g., the pre-registration route.
To test, add this code to any route:
```ts
import { getLayoutContext } from '$lib/contexts/layout';
import { onDestroy } from 'svelte';
const { navigationSettings } = getLayoutContext(onDestroy);
navigationSettings.push({ hide: true});
```
=> feat: add `LayoutContext` option for hiding the nav menu

frontend/src/lib/contexts/layout/layoutContext.ts, frontend/src/lib/contexts/layout/layoutContext.type.ts, frontend/src/routes/[[lang=locale]]/Banner.svelte
Fixes #678 
Add a `cancel` action to `Banner` which can be used to execute an
arbitrary callback, e.g., to cancel the pre-registration process.
The button is very similar to `return` but is a distinct one, because
the former offers some (now updated) default actions and its behaviour
may change in the future.
To test, add the following on any route:
```ts
import { getLayoutContext } from '$lib/contexts/layout';
import { onDestroy } from 'svelte';
const { topBarSettings } = getLayoutContext(onDestroy);
topBarSettings.push({
actions: {
cancel: 'show',
cancelButtonLabel: $t('common.cancel'),
cancelButtonCallback: function() {
console.error('CANCEL!')
},
}
});
```
=> feat: add Cancel registration button to `Banner`

frontend/src/lib/api/utils/authHeaders.ts
=> fix: Node <22 error in `hasAuthHeaders`
